# Generated by Django 4.0.4 on 2022-09-07 11:00

import authenciation.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='otpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=225)),
                ('counter', models.IntegerField(default=0)),
                ('isValid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP',
                'db_table': 'OTP',
            },
            managers=[
                ('otpManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProfileImage', models.ImageField(null=True, upload_to=authenciation.models.profileUploadPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only jpg, jpeg, png are allowed')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('userStatus', models.CharField(choices=[('su', 'Student'), ('te', 'Teacher'), ('fullt', 'Full time job'), ('part', 'Part time job'), ('o', 'Other')], max_length=225)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=225)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userRelated', related_query_name='userQuery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
    ]
