# Generated by Django 4.0.4 on 2022-09-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenciation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpmodel',
            options={'verbose_name_plural': 'OTP'},
        ),
    ]
