# Generated by Django 4.0.4 on 2022-09-08 18:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenciation', '0002_alter_otpmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(validators=[django.core.validators.RegexValidator(message='Only letter, number', regex='^[A-Za-z0-9]{5,1000}\\.[A-Za-z0-9]{5,1000}$')])),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userHelpRelated', related_query_name='userHelpQuery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Help',
                'db_table': 'help',
            },
        ),
    ]
