# Generated by Django 4.0.4 on 2022-09-08 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenciation', '0003_helpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmodel',
            name='detail',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Only letter, number', regex='^[A-Za-z0-9]\\s{5,1000}\\.[A-Za-z0-9]\\s{5,1000}$')]),
        ),
    ]
