# Generated by Django 4.0.4 on 2022-09-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenciation', '0005_alter_helpmodel_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpmodel',
            old_name='email',   
            new_name='username',
        ),
    ]
