# Generated by Django 4.0.4 on 2022-09-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenciation', '0006_rename_email_helpmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmodel',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
