import Head from "next/head"
import dynamic from "next/dynamic"
import { useSelector } from "react-redux"
import { authenciated, AUTHENCIATED } from "@/redux/reducers/authSlice"

import { wrapper } from "@/redux/store"
import { sessionVerficiation } from "@/redux/api/redux.user"

const Appbar = dynamic(() => import('@/components/Comman/Bar'))
const Navbar = dynamic(() => import('@/components/Comman/Navbar'))
const Footer = dynamic(() => import('@/components/Comman/Footer'))

export default function Privacy() {
    const isAuthenciated = useSelector(authenciated) ?? false
    return (
        <>
            <Head>
                <title>TailCode | Privacy</title>
                <meta name='description' content='Privacy TailCode' />
            </Head>
            {isAuthenciated ? <Appbar /> : <Navbar />}
            <main className="min-h-screen my-12 w-[80%] lg:w-1/2 mx-auto space-y-4">
                <h1 className="text-2xl text-black dark:text-white font-medium">Privacy Policy</h1>
                <p className="text-sm text-black dark:text-white">Last updated: September 10, 2022</p>
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                <h1 className="text-xl text-black dark:text-white font-medium">Interpretation and Definitions</h1>
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                <h2 className="text-xl text-black dark:text-white font-medium">Definitions</h2>
                <p className="text-sm text-black dark:text-white">For the purposes of this Privacy Policy:</p>
                <ul className="space-y-1 ml-3">
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to TailCode.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Country</strong> refers to: Jammu and Kashmir,  India</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Service</strong> refers to the Website.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>Website</strong> refers to TailCode, accessible from <a href="localhost:3000" rel="noreferrer nofollow noopener" target="_blank">localhost:3000</a></p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                    </li>
                </ul>
                <h1 className="text-xl text-black dark:text-white font-medium">Collecting and Using Your Personal Data</h1> 
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className="space-y-1">
                    <li>
                        <p>Email address</p>
                    </li>
                    <li>
                        <p>First name and last name</p>
                    </li>
                    <li>
                        <p>Phone number</p>
                    </li>
                    <li>
                        <p>Address, State, Province, ZIP/Postal code, City</p>
                    </li>
                </ul>
                <h3 className="text-xl text-black dark:text-white font-medium">Tracking Technologies and Cookies</h3>
                <p>We use Cookies to track the activity on Our Service and store certain information.</p>
                <ul className="ml-4 space-y-2">
                    <li><strong className='pr-2 text-black dark:text-white'>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use our Service. </li>
                    <li><strong className='pr-2 text-black dark:text-white'>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.</li>
                </ul>
                <h2 className="text-xl text-black dark:text-white font-medium">Use of Your Personal Data</h2>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="ml-4 space-y-1">
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile applications push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
                    </li>
                    <li>
                        <p><strong className='pr-2 text-black dark:text-white'>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
                    </li>
                </ul>
                <h3 className="text-xl text-black dark:text-white font-medium">Law enforcement</h3>
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                <h2 className="text-xl text-black dark:text-white font-medium">Security of Your Personal Data</h2>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                <h1 className="text-xl text-black dark:text-white font-medium">Children Privacy</h1>
                <p>Our Service does not address anyone under the age of 6. We do not knowingly collect personally identifiable information from anyone under the age of 6. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 6 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parents consent before We collect and use that information.</p>
                <h1 className="text-xl text-black dark:text-white font-medium">Changes to this Privacy Policy</h1>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <h1 className="text-xl text-black dark:text-white font-medium">Contact Us</h1>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul>
                    <li>
                        <p>By email: tailcode@gmail.com</p>
                    </li>
                    <li>
                        <p>By visiting this page on our website: <a href="http://localhost:3000/help" rel="noreferrer nofollow noopener" target="_blank">http://localhost:3000/help</a></p>
                    </li>
                </ul>
            </main>
            <Footer />
        </>
    )
}



export const getServerSideProps = wrapper.getServerSideProps(store => async ({ req, res }) => {
    const result = await sessionVerficiation(req, res)
    switch (result) {
        case 200:
            store.dispatch(AUTHENCIATED(true))
            break;
        case 401:
            break;
        case 400:
        case 429:
        case 500:
            return { redirect: { destination: `/${result}` } }
    }
})