# Generated by Django 4.0.4 on 2022-09-07 11:35

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='only charcter, number, space and [ ]', regex='[a-zA-Z0-9\\[\\-\\]\\s]+')])),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('html', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to=blog.models.bannerUploadPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only jpg, jpeg, png are allowed')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Publish'), ('H', 'Hidden'), ('AD', 'Admin Deleted')], default='D', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogRelated', related_query_name='blogQuery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_on'],
            },
        ),
    ]
