# Generated by Django 4.0.4 on 2022-09-09 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_alter_notifications_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='toUser',
            field=models.ManyToManyField(related_name='notifyUserRelated', related_query_name='notifyQuery', to=settings.AUTH_USER_MODEL),
        ),
    ]
