# Generated by Django 4.0.4 on 2022-09-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notifications_touser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='author',
        ),
    ]
