# Generated by Django 4.0.4 on 2022-06-02 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='directory',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='Invalid file', regex='^.*(\\\\.*)$')]),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='downloadCounter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='Only Letters', regex="^[a-z ,.'-]+$")]),
        ),
    ]
