# Generated by Django 4.0.4 on 2022-06-07 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_projectmodel_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='directory',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='Invalid Name', regex='^.*(\\\\.*)$')]),
        ),
    ]
