# Generated by Django 4.0.4 on 2022-09-11 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_projectmodel_options_remove_projectmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='directory',
            field=models.CharField(blank=True, max_length=225, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Name', regex='^.*(\\\\.*)$')]),
        ),
    ]
