# Generated by Django 4.0.4 on 2022-10-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_projectmodel_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='framework',
            field=models.CharField(default='', max_length=225),
        ),
    ]
