# Generated by Django 4.0.4 on 2022-09-19 08:08

import components.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='componentsCatagory',
            fields=[
                ('name', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid name', regex="^(?=.{1,40}$)[a-zA-Z]+(?:[-'\\s][a-zA-Z]+)*$")])),
                ('image', models.ImageField(null=True, upload_to=components.models.catagoryUploadPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only jpg, jpeg, png are allowed')])),
            ],
            options={
                'verbose_name_plural': 'Component Catagories',
            },
        ),
        migrations.CreateModel(
            name='components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=components.models.imageUploadPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only jpg, jpeg, png are allowed')])),
                ('code', models.TextField()),
                ('isHidden', models.BooleanField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catagoryRelated', related_query_name='catagoryQuery', to='components.componentscatagory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentsRelated', related_query_name='componentsQuery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Components',
            },
        ),
    ]
