# Generated by Django 4.0.4 on 2022-09-19 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='name',
            field=models.CharField(default='', max_length=225, validators=[django.core.validators.RegexValidator(message='Invalid name', regex="^(?=.{1,40}$)[a-zA-Z]+(?:[-'\\s][a-zA-Z]+)*$")]),
            preserve_default=False,
        ),
    ]
