# Generated by Django 4.0.4 on 2022-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_components_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='status',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Public', 'Public')], default='Personal', max_length=10),
        ),
    ]
